version: '3.8'
services:

  # APIs
  notification-api:
    build:
      context: NotificationAPI
      dockerfile: Dockerfile
    ports:
      - "5300:80"
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  email-template-api:
    build:
      context: EmailTemplateAPI
      dockerfile: Dockerfile
    ports:
      - "5298:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - smtp4dev

  email-sender-api:
    build:
      context: EmailSenderAPI
      dockerfile: Dockerfile
    ports:
      - "5299:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - smtp4dev

  message-queue-api:
    build:
      context: MessageQueueAPI
      dockerfile: Dockerfile
    ports:
      - "5301:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # Databases
  postgres-client1:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: client1.imscase.dk
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  postgres-client2:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: client2.imscase.dk
    ports:
      - "5431:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  # Utilities
  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - '3000:80'
      - '2526:25'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

# Volumes
volumes:
  smtp4dev-data:
  postgres_data1:
  postgres_data2:  